### ISSUE TITLE
Is this the official Foocus sampler?

### ISSUE THREAD

**Issue by GerardPSU** [hustille/ComfyUI_Fooocus_KSampler#4]
Or is it just 2 advanced k samplers?

**Comment by hustille** [comment]
Yes, this is copied almost verbatim from Fooocus. There are a few bits beyond just mashing two samplers together, but if you want to know what these are, you'd have to read the source - I don't really understand the math.

If I missed something, I'd appreciate a heads up. It's entirely possible, since this sampler so far refuses to play nice with controlnet ...
